plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmPublishRegistry: https://registry.npmjs.org/
npmAuthToken: ${NPM_TOKEN:-invalid}
npmPublishAccess: public
