name: Pull Request
on:
  push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "ci: build"
          git push
